// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLfGGHkKd21i4JZ6E-bsBxHuyHxHk1IuU',
    appId: '1:987400162658:web:7d6daf7ae97331f181f03b',
    messagingSenderId: '987400162658',
    projectId: 'watchncook-733c9',
    authDomain: 'watchncook-733c9.firebaseapp.com',
    storageBucket: 'watchncook-733c9.appspot.com',
    measurementId: 'G-CWV9SRF7SY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2KXLDfUSxy0bZIf1SNpx2U6y3Y9y0BBs',
    appId: '1:987400162658:android:41af564408c07d0881f03b',
    messagingSenderId: '987400162658',
    projectId: 'watchncook-733c9',
    storageBucket: 'watchncook-733c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzxd7gfFdjBjKDtOAjKRhDB-Tn5FPfmLk',
    appId: '1:987400162658:ios:e55f50489f8dc5eb81f03b',
    messagingSenderId: '987400162658',
    projectId: 'watchncook-733c9',
    storageBucket: 'watchncook-733c9.appspot.com',
    iosBundleId: 'com.example.watchncookAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzxd7gfFdjBjKDtOAjKRhDB-Tn5FPfmLk',
    appId: '1:987400162658:ios:ad2bdbba85080f1f81f03b',
    messagingSenderId: '987400162658',
    projectId: 'watchncook-733c9',
    storageBucket: 'watchncook-733c9.appspot.com',
    iosBundleId: 'com.example.watchncookAdmin.RunnerTests',
  );
}
